### ISSUE TITLE
[1.15.2] Crash Relating to ItemPhysicLite

### ISSUE THREAD

**Issue by wademason** [CreativeMD/FriendlyEndermite#2]
**Description**
Crash when rendering dropped items.
Success when building from 1.15.2 branch. Decompiling jar references an _itemtransformer.js_ file requiring ItemPhysicLite.

**To Reproduce**
1. Install FriendlyEndermite on the latest version of Forge (31.1.49).
2. Destroy any block.

**Mod Versions**
- Forge 31.1.49
- FriendlyEndermite 1.0.0

**Logs**
[https://gist.github.com/WadeMason/5016f50f2592ddd49643a9e54454c920](https://gist.github.com/WadeMason/5016f50f2592ddd49643a9e54454c920)

**Comment by CreativeMD** [comment]
Oh damn, thank you very much for your report. Unfortunately I put the core mods from ItemPhysicLite in there. Release a new fixed version. Again thank you, somebody reported this issue a few days ago but I couldn't link it to FriendlyEndermite.
