### ISSUE TITLE
Friendly Endermite generating a lot of logs

### ISSUE THREAD

**Issue by sharlin073** [CreativeMD/FriendlyEndermite#3]
It seems like the mod is generating a lot of logs (log spam?)

I have very limited knowledge in modding if not zero, so I'm just attaching a log here.
I don't think this is causing any kind of problem yet, but I just found out while I was checking why the server froze and the client did not notice it. (still not sure about that though)

Log: (I'm not sure which part is important, but I guess we can look from the bottom)
https://gist.github.com/sharlin073/c8ddec379249300e37e4c5bfbbf0053d

If this is not an issue, I'm sorry!

**Comment by CreativeMD** [comment]
I'm pretty sure that this has nothing to do with FriendlyEndermite.
