### ISSUE TITLE
STDERR generated in the logs

### ISSUE THREAD

**Issue by sfiomn** [CreativeMD/FriendlyEndermite#4]
Hello,

I see on the logs of my local server, a bunch of this error :

https://gist.github.com/sfiomn/2b44d4ab0d06df3c93c4148847d06126

I don't know the implication of this error. Might be worth to take a look.

**Comment by CreativeMD** [comment]
Which version of the game and mod are you using?

**Comment by sfiomn** [comment]
forge 36.1.4 & minecraft 1.16.5
There is also a long list of mods.
The mods about the ender are :
- betterend forge version (latest)
- end remastered
- repurposed structures
- endergetic
- forge ender tech

The mods about other animals are:
- Animal better plus
- Alex's mob
- champions forge version
- infernal mobs
- deadly end phantoms

The mods about targeting are:
- cleancut
- itemphysics

**Comment by CreativeMD** [comment]
Does this issue occur if just FriendlyEndermite is installed, I feel like the "end remastered" mod could interfere there.

**Comment by sfiomn** [comment]
By removing the EndRemastered mod, I still see this error in the logs

**Comment by CreativeMD** [comment]
And what if just FriendlyEndermite is installed?

**Comment by sfiomn** [comment]
Still there, good point.

With only FriendlyEndermite mod in the mod folder, I still have this error in the latest.log.

**Comment by CreativeMD** [comment]
Ok, I will look into it soon. But I'm currently very busy with LittleTiles which has a big release next week. So not sure if I will get to it before it, otherwise I will do it soon afterwards.

**Comment by sfiomn** [comment]
Yeah no problem 👍  
I fear more the error in itemphysics (https://github.com/CreativeMD/ItemPhysic/issues/147#issue-853577014)
than the one in FriendlyEndermite.

**Comment by CreativeMD** [comment]
Thank you very much! Fixed in the newest version.
