### ISSUE TITLE
Game Crashes when starting game.

### ISSUE THREAD

**Issue by GamerGaven** [CreativeMD/FriendlyEndermite#5]
Game crashes only using this mod and the latest forge version.
Here's the crash report:
[crash-2021-12-05_19.01.20-fml.txt](https://github.com/CreativeMD/FriendlyEndermite/files/7657690/crash-2021-12-05_19.01.20-fml.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
